version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
  microservicoa:
    image: "rawallon/microsservicos-avancadev-a"
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - rabbitmq
  microservicob:
    image: "rawallon/microsservicos-avancadev-b"
    ports:
      - "9091:9091"
    restart: on-failure
    depends_on:
      - rabbitmq
  microservicoc:
    image: "rawallon/microsservicos-avancadev-c"
    ports:
      - "9092:9092"
    restart: on-failure
    depends_on:
      - rabbitmq